### ISSUE TITLE
Online compiled documentation

### ISSUE THREAD

**Issue by joaolevada** [graphics32/graphics32.github.io#1]
Hello, folks!

Is there working link for the current compiled documentation? I'm asking, because the one on the repo main page (READme.md) is not working.

Right now, I will clone this repo and give it a shot. Hope that will lead me to a fully working local documentation.

**Comment by CWBudde** [comment]
Sorry there was a typo in the link (it was index.html where it should have been index.htm). With this it should be working in a few minutes (when the github.io content has been refreshed) under https://graphics32.github.io (if you access the documentation from github directly you will get the source code, obviously).
